on: [workflow_dispatch]

name: Publish Report to GitHub Pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0' # The R version to download (if necessary) and use.

      - name: Install packages
        run: |
          Rscript -e 'install.packages(c("tidyverse", "dplyr", "gt", "sf", "ggmap", "tmap", "osmdata", "tidycensus", "leaflet", "ggthemes", "viridis", "knitr"))'

      - name: Render document
        uses: quarto-dev/quarto-actions/render@v2
        env:
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
        with:
          to: html
          path: Assignment6_CharlyVang.Rmd

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./docs
          publish_branch: gh-pages
