on: [workflow_dispatch]

name: Render Report

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    permissions:
        contents: write
        
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0' # The R version to download (if necessary) and use.

      - name: Install packages
        run: |
          Rscript -e 'install.packages(c("knitr", "rmarkdown", "dplyr", "tidyr", "ggplot2", "lubridate", "googleway", "purrr", "leaflet", "gepaf"))'
          
      - name: Render document
        uses: quarto-dev/quarto-actions/render@v2
        env:
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
        with:
          to: html
          path: Assignment6_CharlyVang.Rmd
          
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
      - name: Commit
        run: |
          git add .
          git commit -m "Updated report"
          git push origin main



